
GET http://localhost:3001/matches

###

GET http://localhost:3001/matches/64b941032b4a85d97fa44600

###
POST http://localhost:3001/matches
Content-Type: application/json

{
    "oppositionTeam": "St. Eunan's GAA"
}

###

DELETE http://localhost:3001/matches/64b92c562b4a85d97fa445fb

###

PATCH http://localhost:3001/matches/64b941032b4a85d97fa44600
Content-Type: application/json

{
    "teamOneName": "Limerick",
    "teamTwoName": "Kilkenny"
}